#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
name: Sync with upstream

on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:
permissions:
  actions: write
  contents: write
env:
  UPSTREAM_REPO: https://github.com/coolsnowwolf/lede.git
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout origin
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
        token: '${{ secrets.PAT }}'
        #token: '${{ secrets.GITHUB_TOKEN }}'
        #token: '${{ secrets.WORKFLOW_TOKEN }}'
    - name: Set git identity
      run : |
        #git config --global user.email ${{ secrets.EMAIL }} && git config --global user.name github-actions
        git config user.name github-actions
        git config user.email github-actions@github.com
        #git config --local user.email "action@github.com"
        #git config --local user.name "GitHub Action"
    - name: Pull upstream
      run: git pull $UPSTREAM_REPO --no-edit --rebase --strategy-option=ours
    - name: Push commits
      run: git push origin --force
